name: Flutter Android Build

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build-linux-and-andoird:
    runs-on: ubuntu-latest

    env:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE }}

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Install dependencies
        run: |
          flutter pub get
          flutter upgrade

      - name: Prepare env
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Build APK
        run: |
          echo "${{ env.KEYSTORE_BASE64 }}" | base64 --decode > mpt.keystore
          export KEYSTORE_PATH=$(realpath mpt.keystore)
          flutter build apk --release --build-name=${{ github.ref_name }}
          mv build/app/outputs/flutter-apk/app-release.apk Meeting_Planning_Tool.apk

      - name: Artifact Android
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Meeting_Planning_Tool.apk
          path: |
            Meeting_Planning_Tool.apk

      - name: Build Linux
        run: |
          flutter build linux --release
          tar -cvzf Meeting_Planning_Tool.tar.gz build/linux/x64/release/bundle

      - name: Artifact Linux
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Meeting_Planning_Tool.tar.gz
          path: |
            Meeting_Planning_Tool.tar.gz